FROM php:8.2-apache

RUN apt-get update && \
    apt-get install -y librabbitmq-dev && \
    pecl install amqp && \
    docker-php-ext-enable amqp

WORKDIR /var/www/html
COPY index.php .

EXPOSE 8000
CMD ["php", "-S", "0.0.0.0:8000"]